# Generated by Django 4.0.3 on 2022-04-11 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hippoqueue', '0002_teacher_officehour_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='email',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='lname',
        ),
    ]
